// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM06oYN3mOzZNQ6rj_sLwYeDqoKTiFXuE',
    appId: '1:309745552251:web:4fdf1b8ca08de3d2b7cbde',
    messagingSenderId: '309745552251',
    projectId: 'intellitrack-15803',
    authDomain: 'intellitrack-15803.firebaseapp.com',
    storageBucket: 'intellitrack-15803.appspot.com',
    measurementId: 'G-8RDKZDDPCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy7-cMO4nLVNOTwmnzo6TdqtpUp2aj6Jg',
    appId: '1:309745552251:android:20f48a2ccfd8cb78b7cbde',
    messagingSenderId: '309745552251',
    projectId: 'intellitrack-15803',
    storageBucket: 'intellitrack-15803.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc1UR8WeAMWJOj-FFJlkWl9aBDrRu4AGQ',
    appId: '1:309745552251:ios:0ff25ac2c516749db7cbde',
    messagingSenderId: '309745552251',
    projectId: 'intellitrack-15803',
    storageBucket: 'intellitrack-15803.appspot.com',
    iosBundleId: 'com.example.IT',
  );
}
